# Generated by Django 6.0.2 on 2026-02-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='feautred_image',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='is_feautred',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
